reps = 100;
%%
simulate_aspectratio('repetitions',reps);
%%
simulate_friction('repetitions',reps);
%%
simulate_restitution('repetitions',reps);
%%
simulate_frequency('repetitions',reps);
%%
simulate_size('repetitions',reps);
%%
simulate_amplitude('repetitions',reps);
%%
simulate_position
%%
simulate_smallshift('repetitions',reps)
%%
plot_all;